workflows:
  ales-masaba-feed-android:
    name: Ales Masaba Animal Feed - Android Build
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17

      vars:
        PACKAGE_NAME: "com.alesmasaba.feed"

    scripts:
      - name: Flutter Version
        script: flutter --version

      - name: Clean
        script: flutter clean

      - name: Download Packages
        script: flutter pub get

      - name: Generate Launcher Icons
        script: dart run flutter_launcher_icons

      - name: Build APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - paulomkenyao@gmail.com
        notify:
          success: true
          failure: true
