workflows:
  ales-masaba-feed-android:
    name: Ales Masaba Animal Feed - Android Build
    max_build_duration: 30
    environment:
      flutter: stable
      vars:
        PACKAGE_NAME: "com.alesmasaba.feed"

    scripts:
      - name: Pakua Vifurushi
        script: flutter pub get

      - name: Tengeneza Aikoni
        script: dart run flutter_launcher_icons

      - name: Jenga APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

    publishing:
      email:
        recipients:
          - paulomkenyao@gmail.com
        notify:
          success: true
          failure: true
